# Generated by Django 6.1 on 2026-09-02 14:25

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.TextField(verbose_name="proveedor")),
                (
                    "task",
                    models.TextField(
                        choices=[
                            ("vision", "Visión"),
                            ("intent", "Intención"),
                            ("correction", "Corrección"),
                        ],
                        verbose_name="tarea",
                    ),
                ),
                ("model", models.TextField(blank=True, null=True, verbose_name="modelo")),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("ok", models.BooleanField()),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
            ],
            options={
                "verbose_name": "llamada al LLM",
                "verbose_name_plural": "llamadas al LLM",
                "db_table": "llm_calls",
            },
        ),
        migrations.CreateModel(
            name="ConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chat_id", models.BigIntegerField()),
                ("telegram_user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "role",
                    models.TextField(
                        choices=[("user", "Usuario"), ("assistant", "Asistente")],
                        verbose_name="rol",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creado",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje de conversación",
                "verbose_name_plural": "mensajes de conversación",
                "db_table": "conversation_messages",
                "indexes": [
                    models.Index(
                        fields=["chat_id", "-created_at"], name="conv_msg_chat_created_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["user", "assistant"])),
                        name="conversation_messages_role_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("daily", "Diaria"),
                            ("gap_check", "Chequeo de huecos"),
                            ("nudge_empty", "Aviso de agenda vacía"),
                        ],
                        verbose_name="tipo",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="fecha objetivo"),
                ),
                ("chat_id", models.BigIntegerField()),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="enviada",
                    ),
                ),
                ("ok", models.BooleanField()),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "db_table": "notifications_log",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ok", True)),
                        fields=("kind", "target_date", "chat_id"),
                        name="notif_log_ok_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="id de Telegram"
                    ),
                ),
                ("display_name", models.TextField(verbose_name="nombre")),
                (
                    "role",
                    models.TextField(
                        choices=[("parent", "Padre/madre"), ("admin", "Administrador")],
                        verbose_name="rol",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creado",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "db_table": "users",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["parent", "admin"])),
                        name="users_role_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("photo", "Foto"),
                            ("text_correction", "Corrección por texto"),
                            ("manual", "Manual"),
                        ],
                        verbose_name="tipo",
                    ),
                ),
                ("telegram_file_id", models.TextField(blank=True, null=True)),
                ("local_path", models.TextField(blank=True, null=True, verbose_name="ruta local")),
                (
                    "raw_llm_output",
                    models.JSONField(blank=True, null=True, verbose_name="salida cruda del LLM"),
                ),
                (
                    "llm_provider",
                    models.TextField(blank=True, null=True, verbose_name="proveedor de LLM"),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("rejected", "Rechazada"),
                            ("failed", "Fallida"),
                        ],
                        db_default="pending",
                        default="pending",
                        verbose_name="estado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="submitted_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="agenda.user",
                        verbose_name="enviada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "fuente",
                "verbose_name_plural": "fuentes",
                "db_table": "sources",
            },
        ),
        migrations.CreateModel(
            name="AgendaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="fecha")),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("bring", "Llevar"),
                            ("homework", "Tarea"),
                            ("event", "Evento"),
                            ("note", "Nota"),
                        ],
                        verbose_name="tipo",
                    ),
                ),
                ("text", models.TextField(verbose_name="texto")),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="vigente"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="agenda.source",
                        verbose_name="fuente",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="superseded_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_entries",
                        to="agenda.source",
                        verbose_name="reemplazada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrada de agenda",
                "verbose_name_plural": "entradas de agenda",
                "db_table": "agenda_entries",
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["entry_date"],
                        name="agenda_entry_date_active_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["bring", "homework", "event", "note"])),
                        name="agenda_entries_kind_check",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["photo", "text_correction", "manual"])),
                name="sources_kind_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed", "rejected", "failed"])),
                name="sources_status_check",
            ),
        ),
    ]
