# Generated by Django 6.1 on 2026-09-02 18:24

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCacheEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True, verbose_name="clave")),
                (
                    "task",
                    models.TextField(
                        choices=[
                            ("vision", "Visión"),
                            ("intent", "Intención"),
                            ("correction", "Corrección"),
                        ],
                        verbose_name="tarea",
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(max_length=64, verbose_name="versión de prompts"),
                ),
                ("provider", models.TextField(verbose_name="proveedor original")),
                ("model", models.TextField(blank=True, null=True, verbose_name="modelo")),
                ("response", models.JSONField(verbose_name="respuesta")),
                ("hits", models.IntegerField(db_default=0, default=0, verbose_name="aciertos")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="último acierto"),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="expira")),
            ],
            options={
                "verbose_name": "entrada de caché",
                "verbose_name_plural": "entradas de caché",
                "db_table": "llm_cache",
            },
        ),
        migrations.AddField(
            model_name="llmcall",
            name="cache_read_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="cache_write_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="llm_cache_key",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="Entrada de llm_cache que produjo la extracción; se borra al descartar.",
                null=True,
                verbose_name="clave de caché",
            ),
        ),
    ]
