# Generated by Django 6.1 on 2026-09-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_llm_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="chat_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Chat de Telegram donde llegó, para reintentar y responder tras un reinicio.",
                null=True,
                verbose_name="chat de origen",
            ),
        ),
    ]
