# Generated by Django 6.1 on 2026-09-02 22:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_source_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcacheentry",
            name="task",
            field=models.TextField(
                choices=[
                    ("vision", "Visión"),
                    ("intent", "Intención"),
                    ("correction", "Corrección"),
                    ("refine", "Refinado con respuestas"),
                ],
                verbose_name="tarea",
            ),
        ),
        migrations.AlterField(
            model_name="llmcall",
            name="task",
            field=models.TextField(
                choices=[
                    ("vision", "Visión"),
                    ("intent", "Intención"),
                    ("correction", "Corrección"),
                    ("refine", "Refinado con respuestas"),
                ],
                verbose_name="tarea",
            ),
        ),
        migrations.CreateModel(
            name="CalendarException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField(unique=True, verbose_name="día")),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("holiday", "Festivo"),
                            ("school_closed", "Sin clase"),
                            ("class_day", "Sí hay clase"),
                        ],
                        verbose_name="tipo",
                    ),
                ),
                ("label", models.TextField(verbose_name="motivo")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creado",
                    ),
                ),
            ],
            options={
                "verbose_name": "excepción del calendario",
                "verbose_name_plural": "excepciones del calendario",
                "db_table": "calendar_exceptions",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["holiday", "school_closed", "class_day"])),
                        name="calendar_exceptions_kind_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(verbose_name="nombre")),
                (
                    "anchor_monday",
                    models.DateField(
                        help_text="Lunes de la primera semana del ciclo (la etiquetada con week_index 0).",
                        verbose_name="lunes ancla",
                    ),
                ),
                (
                    "cycle_weeks",
                    models.SmallIntegerField(
                        db_default=2, default=2, verbose_name="semanas del ciclo"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="vigente desde")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="vigente hasta")),
                (
                    "holiday_policy",
                    models.TextField(
                        choices=[
                            ("skip_day", "Solo se cancela ese día"),
                            ("shift", "La rotación se corre"),
                        ],
                        db_default="skip_day",
                        default="skip_day",
                        verbose_name="política de festivos",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="vigente"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="agenda.source",
                        verbose_name="fuente",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="superseded_by",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_schedules",
                        to="agenda.source",
                        verbose_name="reemplazada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "horario",
                "verbose_name_plural": "horarios",
                "db_table": "schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "week_index",
                    models.SmallIntegerField(verbose_name="semana del ciclo (0 = la primera)"),
                ),
                ("week_label", models.TextField(verbose_name="etiqueta de la semana")),
                (
                    "weekday",
                    models.SmallIntegerField(verbose_name="día (ISO: 1 lunes ... 7 domingo)"),
                ),
                ("rotation", models.TextField(blank=True, null=True, verbose_name="rotación")),
                ("subject", models.TextField(verbose_name="materia")),
                ("note", models.TextField(blank=True, null=True, verbose_name="nota")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="agenda.scheduletemplate",
                        verbose_name="horario",
                    ),
                ),
            ],
            options={
                "verbose_name": "franja del horario",
                "verbose_name_plural": "franjas del horario",
                "db_table": "schedule_slots",
            },
        ),
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["valid_from"],
                name="schedule_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("holiday_policy__in", ["skip_day", "shift"])),
                name="schedules_holiday_policy_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("cycle_weeks__gte", 1)), name="schedules_cycle_check"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleslot",
            constraint=models.UniqueConstraint(
                fields=("schedule", "week_index", "weekday"), name="schedule_slot_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 1), ("weekday__lte", 7)),
                name="schedule_slot_weekday_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("week_index__gte", 0)), name="schedule_slot_week_index_check"
            ),
        ),
    ]
