# Generated by Django 6.1 on 2026-09-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0005_schedule_multi"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcall",
            name="prompt",
            field=models.TextField(blank=True, null=True, verbose_name="prompt enviado"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="response",
            field=models.JSONField(blank=True, null=True, verbose_name="respuesta cruda"),
        ),
    ]
