# Generated by Django 6.1 on 2026-09-03 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0006_llm_trace"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduletemplate",
            name="schedules_holiday_policy_check",
        ),
        migrations.RemoveField(
            model_name="scheduletemplate",
            name="holiday_policy",
        ),
    ]
