# Generated by Django 6.1 on 2026-09-03 01:49

"""Vista de solo lectura sobre `checkpoints`, la tabla que crea LangGraph.

`managed = False`, así que esta migración **no toca la base**: solo registra el modelo en el
estado de Django para que el admin pueda listarlo y `makemigrations --check` quede limpio.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0007_drop_holiday_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphThread",
            fields=[
                (
                    "thread_id",
                    models.TextField(primary_key=True, serialize=False, verbose_name="chat"),
                ),
                ("checkpoint_id", models.TextField(verbose_name="checkpoint")),
                ("checkpoint", models.JSONField(verbose_name="estado interno")),
                ("metadata", models.JSONField(verbose_name="metadatos")),
            ],
            options={
                "verbose_name": "conversación en curso",
                "verbose_name_plural": "conversaciones en curso",
                "db_table": "checkpoints",
                "managed": False,
            },
        ),
    ]
