# Generated by Django 6.1 on 2026-09-03 03:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0009_multi_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="monthly_call_limit",
            field=models.IntegerField(
                db_default=500,
                default=500,
                help_text="Aunque cada familia pague su API, el disco y la CPU son del anfitrión.",
                verbose_name="límite de llamadas al mes",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="text_provider",
            field=models.TextField(
                choices=[
                    ("anthropic_api", "Anthropic (API)"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama propio"),
                ],
                db_default="anthropic_api",
                default="anthropic_api",
                verbose_name="proveedor de texto",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="uses_host_llm",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Solo para la familia del operador: usa la suscripción configurada en el .env en vez de una clave propia. Ceder esa suscripción a terceros va contra sus términos de uso.",
                verbose_name="usa el LLM del anfitrión",
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="vision_provider",
            field=models.TextField(
                choices=[
                    ("anthropic_api", "Anthropic (API)"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama propio"),
                ],
                db_default="anthropic_api",
                default="anthropic_api",
                verbose_name="proveedor de visión",
            ),
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.TextField(
                        choices=[
                            ("anthropic_api", "Anthropic (API)"),
                            ("openai", "OpenAI"),
                            ("ollama", "Ollama propio"),
                        ],
                        verbose_name="proveedor",
                    ),
                ),
                (
                    "secret",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Cifrada con Fernet.",
                        verbose_name="clave cifrada",
                    ),
                ),
                (
                    "base_url",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Solo para Ollama.",
                        verbose_name="URL base",
                    ),
                ),
                (
                    "vision_model",
                    models.TextField(blank=True, default="", verbose_name="modelo de visión"),
                ),
                (
                    "text_model",
                    models.TextField(blank=True, default="", verbose_name="modelo de texto"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_default=True, default=True, verbose_name="activa"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="creada",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizada")),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credentials",
                        to="agenda.family",
                        verbose_name="familia",
                    ),
                ),
            ],
            options={
                "verbose_name": "clave de LLM",
                "verbose_name_plural": "claves de LLM",
                "db_table": "credentials",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "provider"), name="credential_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider__in", ["anthropic_api", "openai", "ollama"])),
                        name="credential_provider_check",
                    ),
                ],
            },
        ),
    ]
